OBJS=font.o vgft.o graphics.o
LIB=libvgfont.a

INCLUDES+=-I$(SDKSTAGE)/usr/include/freetype2 -I$(SDKSTAGE)/usr/include -I$(SDKSTAGE)/usr/include/arm-linux-gnueabi

include /home/pi/vc/src/hello_pi/Makefile.include

